server:
  port: 8010
spring:
  application:
    name: products
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/app
